### ISSUE TITLE
Question about recall @ k

### ISSUE THREAD

**Issue by jmhessel** [fartashf/vsepp#14]
Hi There! Thanks for the code :)

I'm curious about how evaluation works in this library. Based on a comment [here](https://github.com/fartashf/vsepp/issues/11#issuecomment-368723408) I think that the input matrices in `t2i` and `i2t` are the same, and the image features are copied 5x. In `t2i`, it looks like the images are downsampled into a matrix consisting of only a single copy of each image, which makes sense for image retrieval. However, in caption retrieval, it looks like each image is used to search all of the captions, of which, there are 5 correct ones. [This part of the code](https://github.com/fartashf/vsepp/blob/5e4d4da94baf5969fac086870519e3dfab4b24d8/evaluation.py#L238-L244) appears to find, among the 5 correct captions for MSCOCO, the best/lowest ranked one among the 5K possibilities.

However -- I am a bit confused because I don't think that this corresponds to the definition of `R@k` (e.g., for `k=1,5,10`)... If there are 5 correct answers, I think the maximal recall-at-1 is `1/5`? Perhaps I am misunderstanding the code, e.g., how the cross-validation splits are set up, and/or what is standard for cross-modal retrieval work. What do you think?

**Comment by fartashf** [comment]
The definition of precision and recall here are closer to what is used in NLP and in defining metrics such as ROUGE_L and ROUGE_S. In that context, a model is returning a sequence of tokens (words) and it is evaluated based on how similar that sequence is to one or multiple ground-truth sequences. If there are multiple ground-truth sequences, the score is the maximum of the score with any of the ground-truths. In the case of caption retrieval, it is common to use this in-between precision-recall metric that's treating full-length sequences as single tokens. That is just due to the simplification made to the task where instead of generating the captions, we use a database of ready-to-use captions. But it still makes more sense to use the ROUGE version of the precision-recall metrics rather than the document retrieval version.

Lin 2004, "ROUGE: A Package for Automatic Evaluation of Summaries"
Chen 2015, "Microsoft COCO Captions: Data Collection and Evaluation Server"

**Comment by jmhessel** [comment]
Thanks for the reply! I see what you mean, and -- looking back at even early retrieval reporting on MSCOCO (e.g., Karpathy and Li 2015) -- the score is clearly not capped at .2. I agree that this metric makes sense, though it definitely shouldn't be called recall IMO. Perhaps "hit-rate-at-k" is better? Anyway -- this seems to be a problem that I have with nomenclature more than anything else. Thanks again for the code!!! :)

**Comment by fartashf** [comment]
Yeah. I agree that it's confusing.
