### ISSUE TITLE
meanr and rsum seem inversely correlated

### ISSUE THREAD

**Issue by BigRedT** [fartashf/vsepp#16]
Hi @fartashf,

Great code base, very easy to work with! I had two quick questions regarding evaluation metrics:

- I noticed that meanr increases as rsum increases and was wondering if you had an explanation for this? (See plots below) I should mention that these results are with a few modifications to your code. Specifically, I used Glove embeddings where the embeddings are not trained / "backproped" into. 

- Also was wondering what was the reason for choosing rsum for model selection instead of meanr?

<img width="342" alt="screen shot 2019-01-17 at 12 48 21 pm" src="https://user-images.githubusercontent.com/5041894/51341461-f9aec180-1a56-11e9-9281-9e5389eeb8a4.png">

<img width="343" alt="screen shot 2019-01-17 at 12 48 43 pm" src="https://user-images.githubusercontent.com/5041894/51341466-fd424880-1a56-11e9-9c3c-c5b665e69815.png">

Thanks!

**Comment by fartashf** [comment]
Thanks for using the code.

This is not unexpected, but the difference between the min and max of `meanr` (~7 in rank) might be too much and worth further inspection. I suggest running a clean clone and comparing the plots. I'm not absolutely certain but I don't think you would see a gap more than 2.

It is expected because the MH loss in VSE++ optimizes R@1. If you care about the average rank, the SH loss in VSE0 is more appropriate.  `meanr` is an average rank for all retrieved items while `rsum` is the sum of R@1+R@5+R@10. `meanr` is affected by outliers. If we retrieve an item at 1000 and improve the model and get it to 900, `meanr` is slightly improved while `rsum` is not.

In hindsight, it might have been more appropriate to use R@1 for early stopping instead of `rsum`. `rsum` was originally used for model selection in the UVS code.

For reference, these lines compute the metrics: https://github.com/fartashf/vsepp/blob/226688a0f26aa1c32d34fbe723795dc65702504c/evaluation.py#L246 and https://github.com/fartashf/vsepp/blob/226688a0f26aa1c32d34fbe723795dc65702504c/train.py#L202

**Comment by BigRedT** [comment]
Thanks that was very helpful!

**Comment by fartashf** [comment]
Yes. Only the minimum rank is caption retrieved with the lowest rank is used for evaluation.
